services:
  web:
    image: httpd:2.4
    ports:
      - 8080:80
    volumes:
      - logs:/var/log/apache2
      - ./apache/vhost.conf:/usr/local/apache2/conf/httpd.conf:ro
    depends_on:
      - api
  api:
    image: kennethreitz/httpbin
    ports:
      - 8081:80
  grok:
    build:
      context: grok_exporter
    volumes:
      - logs:/var/log/apache2

volumes:
  logs: