services:
  web:
    image: httpd:2.4
    ports:
      - "8080:80"
    volumes:
      - logs:/usr/local/apache2/logs/
      - ./apache/vhost.conf:/usr/local/apache2/conf/httpd.conf:ro
    depends_on:
      - api
  api:
    image: kennethreitz/httpbin
    ports:
      - "8081:80"
  grok:
    build:
      context: grok_exporter
    volumes:
      - logs:/usr/local/apache2/logs/
      - ./grok_exporter/config.yml:/grok_exporter/config.yml
      - ./grok_exporter/patterns/httpd:/grok_exporter/logstash-patterns-core/patterns/legacy/httpd
    command: ["grok_exporter", "-config", "/grok_exporter/config.yml"]
    ports:
      - "9144:9144"

volumes:
  logs: