global:
  config_version: 3
input:
  type: file
  path: /usr/local/apache2/logs/access_log
  fail_on_missing_logfile: false
imports:
- type: grok_patterns
  dir: /grok_exporter/logstash-patterns-core/patterns/legacy
metrics:
- type: counter
  name: apache_http_response_codes_total
  help: HTTP response codes total
  match: '%{HTTPD_COMBINEDLOG}'
  labels:
    method: '{{.verb}}'
    path: '{{.request}}'
    code: '{{.response}}'
- type: histogram
  name: apache_http_response_time
  help: HTTP response time
  match: '%{HTTPD_COMBINEDLOG}'
  value: '{{divide .request_time 1000000}}'
  labels:
    code: '{{.response}}'
server:
  port: 9144