global:
  config_version: 3
input:
  type: file
  path: /usr/local/apache2/logs/access_log
  readall: true
  fail_on_missing_logfile: false
imports:
- type: grok_patterns
  dir: /grok_exporter/logstash-patterns-core/patterns/legacy
metrics:
- type: counter
  name: apache_http_response_codes_total
  help: HTTP requests to Apache
  match: '%{HTTPD_COMBINEDLOG}'
  labels:
    method: '{{.verb}}'
    path: '{{.request}}'
    code: '{{.response}}'
server:
  port: 9144